### ISSUE TITLE
Not working for other users

### ISSUE THREAD

**Issue by reduardo7** [onesc34567/google-sheet-api#1]
Some users are getting following error on access to the link:

![Image Pasted at 2023-9-19 10-05](https://github.com/onescales/google-sheet-api/assets/2788937/94bd9e37-c413-4471-a263-d12cfd8c4075)

**Comment by oritzv** [comment]
looks like a general error message to come back again later. can you specify how many entries/rows you have in your sheet and how often it gets updated? may or may not be over usage

**Comment by reduardo7** [comment]
> looks like a general error message to come back again later. can you specify how many entries/rows you have in your sheet and how often it gets updated? may or may not be over usage

Thanks for your answer! I have a simple sheet with only 2 columns and 3 rows.

**Comment by oritzv** [comment]
is it ok to share the url so i can check?

**Comment by reduardo7** [comment]
> is it ok to share the url so i can check?

Sure! The following is the sheet: https://docs.google.com/spreadsheets/d/1LcIN2ZtQiElOVIozbyu1XLq4jiB0HWtofzmyI5VeTT8/edit#gid=0

The following is the API URL: https://script.google.com/macros/s/AKfycbz1FQmP0UDMT4-rmB3HKIjv84CFVEoX3FGKzTuKjkQ1uHZQ70p2CdvU_0xeZ0rrGKDx/exec

And the following is the minimum script:
```javascript
function json() {
  const spreadsheet = SpreadsheetApp.getActiveSpreadsheet()
  const sheet = spreadsheet.getSheetByName('s1')
  const data = sheet.getDataRange().getValues()
  const jsonData = convertToJson(data)
  return ContentService
        .createTextOutput(JSON.stringify(jsonData))
        .setMimeType(ContentService.MimeType.JSON)
}

function convertToJson(data) {
  const headers = data[0]
  const raw_data = data.slice(1,)
  let json = []
  raw_data.forEach(d => {
      let object = {}
      for (let i = 0; i < headers.length; i++) {
        object[headers[i]] = d[i]
      }
      json.push(object)
  });
  return json
}

function doGet(e) {
  //const key = e.parameter.key
  return json()
}
```

Some users are getting the error, and it works for most.

**Comment by oritzv** [comment]
i've visited the url multiple times over last few days and it always looks good. is it still an issue on your end?

**Comment by reduardo7** [comment]
> i've visited the url multiple times over last few days and it always looks good. is it still an issue on your end?

Thank you for your support! It was probably a problem on Google's side as now it seems to be working fine.
